export const paths = {
    home: "/",
    sport: "/sport",
    athleteRank: "/athleterank",
    courtSurface: "/courtsurface",
    sportsFacilityType: "/sportsfacilitytype",
    sportClub: "/sportclub",
    sportsFacility: "/sportsfacility",
    court: "/sportsfacility/court",
    gym: "/sportsfacility/gym",
    stadium: "/sportsfacility/stadium",
    arena: "/sportsfacility/arena",
    athlete: "/athlete",
    athleteRanking: "/athleteranking",
    trainer: "/trainer",
    trainerLicense: "/trainerlicense",
    training: "/training",
    sponsor: "/sponsor",
    competition: "/competition",
    competitionPlayer: "/competitionPlayer",
}

export const reportPaths = {
    sportsFacilityByFieldValue: "/report/sportsfacility/null",
    athleteBySportAndRanking: "/report/athlete/bysport",
    athleteByTrainerAndRanking: "/report/athlete/bytrainerlicense",
    athleteWhoMoreThanOneSport: "/report/athlete/morethanone",
    trainerByAthlete: "/report/trainer/byathlete",
    competitionByPeriod: "/report/competition/byperiod",
    athleteWhoWinnerByCompetition: "/report/athlete/bycompetition",
    competitionBySportsFacility: "/report/competition/byfacility",
    sportClubWithAthleteCountByPeriod: "/report/sportclub/byperiod",
    trainerBySport: "/report/trainer/bysport",
    athleteWhoNotInCompetitionByPeriod: "/report/athlete/notincompetitionbyperiod",
    sponsorByCompetitionPeriod: "/report/sponsor/byperiod",
    sportsFacilityByCompetitionPeriod: "/report/sportsfacility/bycompetitionperiod",
}